abstract class MobilState{}
class initState extends MobilState{}
class changeObsr extends MobilState{}
class ChangePosition extends MobilState{}
class ChangeVisibalBar extends MobilState{}
class ChangeActived extends MobilState{}
class clopsed extends MobilState{}
class ChangeSelectedTile extends MobilState{}
class SignInTr extends MobilState{}
class SignInFa extends MobilState{}
class GetUserDateTr extends MobilState{}
class GetUserDateFa extends MobilState{}
class GetMoneyDateFa extends MobilState{}
class GetMoneyDateTr extends MobilState{}
class GetOrderItemDateFa extends MobilState{}
class GetOrderItemDateTr extends MobilState{}
class GetProductDateTr extends MobilState{}
class GetProductDateFa extends MobilState{}
class UpdateProductDateTr extends MobilState{}
class UpdateProductDateFa extends MobilState{}
class GetSuppliersDateTr extends MobilState{}
class GetSuppliersDateFa extends MobilState{}
class GetFessDateTr extends MobilState{}
class GetFessDateFa extends MobilState{}
class GetEmployeeDateTr extends MobilState{}
class GetEmployeeDateFa extends MobilState{}
class GetAttendanceDateTr extends MobilState{}
class GetAttendanceDateFa extends MobilState{}
class GetRateDateTr extends MobilState{}
class GetRateDateFa extends MobilState{}
